import type { PublicationData } from "../types";

export function publicationFixture(): PublicationData {
  const rootId = "release:view:root";
  return {
    schema_version: 2,
    dataset_sha256: "a".repeat(64),
    release: { release_id: "release", year: 2026, phase: "approved_initial", publication: "Lei" },
    view: {
      view_id: "view",
      official_name: "Mapa 1",
      dimension: "programmatic",
      root_node_id: rootId,
      selectable: true,
      coverage: {
        institutional_universe: "administracao_central",
        social_security: "excluded",
        consolidation: "non_consolidated",
        measure: "budgeted_expenditure",
        accounting_classification: "mapa",
        gross_net: "not_declared_by_source",
        currency: "EUR",
        unit: "cents",
      },
    },
    nodes: [
      {
        node_id: rootId,
        official_code: null,
        official_label: "Total da Administração Central",
        amount_cents: 1_000,
        level: 0,
        parent_node_id: null,
        sort_order: 0,
        is_terminal: false,
        factual_tags: [],
        source: { source_id: "pdf", locator: "página 1" },
      },
      {
        node_id: "release:view:area",
        official_code: "P-001",
        official_label: "Saúde",
        amount_cents: 600,
        level: 1,
        parent_node_id: rootId,
        sort_order: 1,
        is_terminal: false,
        factual_tags: ["Despesa condicionada por compromissos legais"],
        source: { source_id: "xml", locator: "/Mapa1/Registo[1]" },
      },
      {
        node_id: "release:view:area:acao-1",
        official_code: "A-001",
        official_label: "Cuidados de saúde primários",
        amount_cents: 200,
        level: 2,
        parent_node_id: "release:view:area",
        sort_order: 1,
        is_terminal: true,
        factual_tags: ["Inclui transferências legalmente previstas"],
        source: { source_id: "xml", locator: "/Mapa1/Registo[1]/Acao[1]" },
      },
      {
        node_id: "release:view:area:acao-2",
        official_code: "A-002",
        official_label: "Cuidados hospitalares",
        amount_cents: 400,
        level: 2,
        parent_node_id: "release:view:area",
        sort_order: 2,
        is_terminal: true,
        factual_tags: [],
        source: { source_id: "xml", locator: "/Mapa1/Registo[1]/Acao[2]" },
      },
      {
        node_id: "release:view:P-002",
        official_code: "P-002",
        official_label: "Educação",
        amount_cents: 400,
        level: 1,
        parent_node_id: rootId,
        sort_order: 2,
        is_terminal: true,
        factual_tags: [],
        source: { source_id: "xml", locator: "/Mapa1/Registo[1]" },
      },
    ],
    sources: [
      { source_id: "pdf", publisher: "Entidade oficial", title: "Mapa PDF", url: "https://dados.gov.pt/mapa.pdf", coverage: "Total", reuse_terms: "public_domain" },
      { source_id: "xml", publisher: "Entidade oficial", title: "Mapa XML", url: "https://dados.gov.pt/mapa.xml", coverage: "Programas", reuse_terms: "public_domain" },
    ],
  };
}
